# Generated by Django 5.2.17 on 2026-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_documents',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='max_storage_bytes',
            field=models.BigIntegerField(default=50000000),
        ),
        migrations.AddField(
            model_name='user',
            name='used_storage_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
