# Generated by Django 5.2.17 on 2026-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20),
        ),
    ]
