# Generated by Django 5.2.17 on 2026-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_error_message_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='page',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro de page du PDF d'origine", null=True),
        ),
    ]
